<?php

namespace Untek\Utility\Log\Domain\Services;

use Untek\Utility\Log\Domain\Entities\HistoryEntity;
use Untek\Utility\Log\Domain\Entities\LogEntity;
use Untek\Utility\Log\Domain\Interfaces\Repositories\HistoryRepositoryInterface;
use Untek\Utility\Log\Domain\Interfaces\Services\HistoryServiceInterface;
use Untek\Model\Service\Base\BaseCrudService;
use Untek\Model\EntityManager\Interfaces\EntityManagerInterface;
use Untek\Model\DataProvider\Libs\DataProvider;
use Untek\Model\Query\Entities\Query;

class HistoryService extends BaseCrudService implements HistoryServiceInterface
{

    public function __construct(EntityManagerInterface $em, HistoryRepositoryInterface $historyRepository)
    {
        $this->setEntityManager($em);
        $this->setRepository($historyRepository);
    }

    public function getEntityClass(): string
    {
        return HistoryEntity::class;
    }

    public function getDataProvider(Query $query = null): DataProvider
    {
        return parent::getDataProvider($query); // TODO: Change the autogenerated stub
    }
}
